name: Friday Rota – Slack reminder

on:
  schedule:
    - cron: "0 7 * * 3"   # Wednesdays 07:00 UTC
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure config exists and inject Slack secret
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          mkdir -p data
          if [ ! -f data/rota_config.json ]; then
            echo '{"members":["Chris","Dylan","Elizma","Leo","Oliver"],"start_member":"Chris","slack_webhook_url":"","slack_id_map":{},"overrides":{}}' > data/rota_config.json
          fi
          python -c "import json, os; p='data/rota_config.json'; f=open(p); cfg=json.load(f); f.close();\
          cfg.setdefault('slack_webhook_url', os.environ.get('SLACK_WEBHOOK_URL',''));\
          open(p,'w').write(json.dumps(cfg, indent=2))"
      - name: Run notifier
        run: python notify.py
